services:
  - type: web
    name: zan-python-host
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 8 --timeout 120
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
